const $ = require('jquery'); // если нужен
const scroll = require('./common/scroll');
const preload = require('./common/preload');
const auth = require('./common/auth');
const parallax = require('./common/parallax');
const menuButton = require('./common/menu');
const sliderMenu = require('./common/articleScroll');
const sidebar = require('./common/sidebar');
const slider = require('./common/slider');